# Generated by Django 3.2.25 on 2024-03-21 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='adress',
            new_name='address',
        ),
    ]
