# Generated by Django 5.0.3 on 2024-03-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policymodel',
            name='last_update',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
