# Generated by Django 3.2.25 on 2024-04-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_policymodel_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('created', 'order created'), ('ordered', 'Order Successful'), ('delivered', 'Delivered Successfully'), ('canceled', 'order canceled')], max_length=50),
        ),
    ]
