# Generated by Django 3.2.25 on 2024-03-22 15:44

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_imagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(upload_to=home.models.product_image_upload_path),
        ),
    ]
