# Generated by Django 3.2.25 on 2024-03-23 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_productmodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodel',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cartmodel',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='product',
        ),
        migrations.CreateModel(
            name='OrderProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderproductmodel_order', to='home.ordermodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderproductmodel_product', to='home.productmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CartProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartproductmodel_cart', to='home.cartmodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartproductmodel_product', to='home.productmodel')),
            ],
        ),
    ]
