# Generated by Django 3.2.25 on 2024-03-23 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20240323_0611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderproductmodel',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
